databases:
  - name: recipe
    databaseName: recipe_eu53
    user: recipe_eu53_user

services:
  - type: web
    name: recipe-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_eu53
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false